"""added history of changes table

Revision ID: 06cdf5faad61
Revises: fc6cb3ed5286
Create Date: 2026-02-03 01:58:21.217265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '06cdf5faad61'
down_revision: Union[str, Sequence[str], None] = 'fc6cb3ed5286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('history_of_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record', sa.Integer(), nullable=False),
    sa.Column('changes_json', sa.JSON(), nullable=True),
    sa.Column('operation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history_of_changes')
    # ### end Alembic commands ###
